//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DabbawallasData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALERTA
    {
        public int ID_ALERTA { get; set; }
        public Nullable<int> ID_CLIENTE_ALERTA { get; set; }
        public Nullable<int> ID_TIPO_ALERTA { get; set; }
        public Nullable<System.DateTime> FECHA_ALERTA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual TIPO_ALERTA TIPO_ALERTA { get; set; }
    }
}
