//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DabbawallasData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.ALERTA = new HashSet<ALERTA>();
            this.TICKET = new HashSet<TICKET>();
            this.TICKET1 = new HashSet<TICKET>();
        }
    
        public Nullable<int> ID_USUARIO { get; set; }
        public int ID_CLIENTE { get; set; }
        public string DIRECCION_HOGAR { get; set; }
        public string DIRECCION_TRABAJO { get; set; }
        public Nullable<int> ID_COMUNA_HOGAR { get; set; }
        public Nullable<int> ID_COMUNA_TRABAJO { get; set; }
        public Nullable<int> ID_ESTADO_SUSCRIPCION { get; set; }
        public Nullable<int> ID_DABBAWALLA_ASOCIADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALERTA> ALERTA { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual COMUNA COMUNA1 { get; set; }
        public virtual DABBAWALLA DABBAWALLA { get; set; }
        public virtual ESTADO_SUSCRIPCION ESTADO_SUSCRIPCION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKET1 { get; set; }
    }
}
