//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DabbawallasData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DABBAWALLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DABBAWALLA()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public Nullable<int> ID_USUARIO { get; set; }
        public int ID_DABBAWALLA { get; set; }
        public Nullable<int> ID_SUPERVISOR_ASOCIADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual SUPERVISOR SUPERVISOR { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
