//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DabbawallasData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPERVISOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPERVISOR()
        {
            this.DABBAWALLA = new HashSet<DABBAWALLA>();
        }
    
        public Nullable<int> ID_USUARIO { get; set; }
        public int ID_SUPERVISOR { get; set; }
        public Nullable<int> ID_ZONA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DABBAWALLA> DABBAWALLA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ZONA ZONA { get; set; }
    }
}
