//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DabbawallasData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_CANTIDAD_CLIENTES_POR_DABBAWALLA
    {
        public int ID_DABBAWALLA { get; set; }
        public Nullable<int> Clientes_Asociados { get; set; }
    }
}
