//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DabbawallasData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_INFORMACION_CLIENTES_SUSCRITOS
    {
        public int ID_CLIENTE { get; set; }
        public string USERNAME_CLIENTE { get; set; }
        public string DIRECCION_HOGAR { get; set; }
        public string COMUNA_HOGAR { get; set; }
        public string DIRECCION_TRABAJO { get; set; }
        public string COMUNA_TRABAJO { get; set; }
        public int ID_DABBAWALLA { get; set; }
        public Nullable<int> ID_SUPERVISOR { get; set; }
        public string ZONA_SUPERVISOR { get; set; }
    }
}
